name: Build and Deploy

on:
  schedule:
    - cron: '05 20 1 * *'  # Runs at 20:05 UTC on the 1st day of every month

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Setup .NET
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # specify your .NET version

    - name: Print current directory before restoring dependencies
      run: pwd

    # Step 3: Restore .NET dependencies
    - name: Restore dependencies
      run: dotnet restore polpriser.csproj

    # Step 4: Build the application
    - name: Build the application
      run: dotnet build --configuration Release

    - name: Create data directory
      run: mkdir priser

    # Step 5: Run your commands sequentially
    - name: Run get-products-json-files
      run: bin/Release/net8.0/polpriser get-products-json-files 

    - name: Run create-database
      run: bin/Release/net8.0/polpriser create-database

    - name: Run extract-product-data
      run: bin/Release/net8.0/polpriser extract-product-data

    - name: Run create-version-file
      run: bin/Release/net8.0/polpriser create-version-file

    # Step 6: Prepare files for deployment
    - name: Prepare files for deployment
      run: |
        mkdir -p publish
        cp vino.db publish/vino13.db
        cp vino.txt publish/vino13.txt

    # Step 7: Deploy to GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: polpriser/polpriser.github.io  # The GitHub Pages repository    
        publish_branch: main  # Push to the main branch of polpriser.github.io
        publish_dir: publish
        
